module.exports.makeCryptographicModuleTemplateAndroid = (key) => {
  return `
// this is autogenerated, dont change within it
package com.reactnativekeysjsi

object PrivateKey {
    const val privatekey = "${key}"
}`;
};
