
// this is autogenerated, dont change within it
package com.reactnativekeysjsi

object PrivateKey {
    const val privatekey = "mkQSGENA8dOzDZMjvZ3oustFgp7KEui9kQkhYCrYVN5vysn7gAVtpo+dkRbzXVPkFvo5Cqs3p9vEgt7PRGwBdEihgPNahO2QbF4e/hZJyw=="
}